### ISSUE TITLE
Selected slot inconsistent

### ISSUE THREAD

**Issue by diogotr7** [XFactHD/LogitechGLights#1]
Hello, really like the project! I was tinkering with this and found that the selected slot feature isnt working totally as it should, but I haven't found a pattern to it.

~~Also, when selecting colors you can't see what was previously selected, it always resets to 255/255/255.~~ I figured out you can just click load, my bad

As a suggestion, health/hunger/armor/potions could be added as effects!

I tested this and it works with [Aurora](https://github.com/antonpup/Aurora) on my g810 whioch means it might be able to be used with other manfacturers of keyboards (Razer, corsair etc).

**Comment by XFactHD** [comment]
The problem with the selected slot feature is that certain things that change the lighting like the player's death may not reset the variable that handles the selected slot. I do not want to unnecessarily eat up processing time just to set the color of that one button every single game tick which is why this is implemented that way. I am glad that there are people that care for such little imperfections so if you find patterns for this incosistent behaviour, just tell me and I'll do my best to fix them.
